# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_group_group1_user_user1_user1_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='blog.Group'),
        ),
    ]
